spring.profiles.group:
  "test": "common,local,local-db-h2"
---
# common
spring:
  config:
    activate:
      on-profile: common
      thymeleaf:
        prefix: classpath:templates/
        suffix: .html
---


---
# Local
spring:
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
    check-template-location: true
  server:
    port: 8080
    undertow:
      threads:
        io: 16
        worker: 400
---
# server
spring:
  profiles:
    active: server
  devtools:
    livereload:
      enable: false

---
# DB - H2
spring:
  profiles:
    active: local-db-h2
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
  jpa:
    showSql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:~/cclt
    username: sa
    password:
    driver-class-name: org.h2.Driver
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace # sql parameter 확인

