# spring group
spring.profiles.group:
  "local": "common,local,h2-console"
  "test": "common,local,h2-console"
---
# common
spring:
  config:
    activate:
      on-profile: common
#    import:
#      - classpath:application-oauth.yml
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  liquibase:
#    change-log: classpath:/db/changelog-master.xml
---
# local
spring:
  config:
    activate:
      on-profile: local
  thymeleaf:
    cache: false
server:
  port : 8080
  undertow:
    threads:
      io: 16
      worker: 400
logging:
  config: classpath:log4j2-local.yml
---

# dev

---
# h2-console
spring:
  profiles:
    active: h2-console
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: false
  datasource:
    url: jdbc:log4jdbc:h2:file:~/Documents/h2db/study;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
---
# local PostgreSQL
spring:
  profiles:
    active: local-db-postgresql
  # DB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/clt
    username: acj
    password: javaBye#
  # Connection Pool
  hikari:
    connection-timeout: 20000
    maximum-pool-size: 10
  #JPA
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual: true