name: CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: setup jdk17
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '17'

      # ./gradlw 실행 권한 부여
      #      - name: Grant execute permission for gradlew
      #        run: chmod +x ./gradlew
      #        shell: bash

      # Spring Boot 어플리케이션 Build (1)
      #      - name: Spring Boot Build
      #        run: ./gradlew clean build --exclude-task test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.OLKK_GITHUB_TOKEN }}

      # Docker Hub push (4)
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest